FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=/api/v1
ARG VITE_API_VERSION=v1
ARG VITE_APP_PLATFORM=web
ARG VITE_APP_NAME="Oasys School Dashboard"
ARG VITE_APP_VERSION=0.1.0
ARG VITE_TOKEN_STORAGE_KEY=oasys_access_token
ARG VITE_REFRESH_TOKEN_STORAGE_KEY=oasys_refresh_token
ARG VITE_TOKEN_EXPIRY_BUFFER_MS=60000
ARG VITE_DEFAULT_PAGE_SIZE=20
ARG VITE_MAX_PAGE_SIZE=100
ARG VITE_ENABLE_PARENT_REGISTRATION_PAGE=true
ARG VITE_ENABLE_ANALYTICS=false
ARG VITE_SENTRY_DSN=

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_API_VERSION=$VITE_API_VERSION \
    VITE_APP_PLATFORM=$VITE_APP_PLATFORM \
    VITE_APP_NAME=$VITE_APP_NAME \
    VITE_APP_VERSION=$VITE_APP_VERSION \
    VITE_TOKEN_STORAGE_KEY=$VITE_TOKEN_STORAGE_KEY \
    VITE_REFRESH_TOKEN_STORAGE_KEY=$VITE_REFRESH_TOKEN_STORAGE_KEY \
    VITE_TOKEN_EXPIRY_BUFFER_MS=$VITE_TOKEN_EXPIRY_BUFFER_MS \
    VITE_DEFAULT_PAGE_SIZE=$VITE_DEFAULT_PAGE_SIZE \
    VITE_MAX_PAGE_SIZE=$VITE_MAX_PAGE_SIZE \
    VITE_ENABLE_PARENT_REGISTRATION_PAGE=$VITE_ENABLE_PARENT_REGISTRATION_PAGE \
    VITE_ENABLE_ANALYTICS=$VITE_ENABLE_ANALYTICS \
    VITE_SENTRY_DSN=$VITE_SENTRY_DSN

RUN npm run build


FROM nginx:1.27-alpine AS runtime

RUN rm -f /etc/nginx/conf.d/default.conf

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -q --spider http://localhost/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
